---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver: 
      box: ubuntu/trusty64
      memory: 4096
      customize:
        natdnshostresolver1: "on"

suites:
  - name: default
    run_list:
      - recipe[apiserver-cookbook::default]
    attributes:
