name 'apiserver-cookbook'
maintainer 'Puneet Sachdev'
maintainer_email 'puneet.sachdev@gmail.com'
license 'all_rights'
description 'Installs/Configures apiserver-cookbook'
long_description 'Installs/Configures apiserver-cookbook'
version '0.1.1'
depends 'apt'
depends 'java'
