---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver: 
      box: "ubuntu/trusty64"
      customize: 
        natdnshostresolver1: "on"

suites:
  - name: default
    run_list:
      - recipe[dbserver-cookbook::default]
    attributes:
